apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-node-app
  template:
    metadata:
      labels:
        app: react-node-app
    spec:
      containers:
        - name: frontend
          image: beyghakymyar/frontend
          ports:
            - containerPort: 3000
        - name: backend
          image: beyghakymyar/backendend
          env:
            - name: MONGODB_URI
              value: mongodb+srv://hyb:7889@cluster0.9aj9ofe.mongodb.net/?retryWrites=true&w=majority
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: react-node-service
spec:
  type: NodePort
  selector:
    app: react-node-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30060
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30061
      